FROM node:16.13.2 as builder
WORKDIR /usr/src/app
ENV VUE_APP_API_URL=/api
COPY . .
RUN npm install --cache /usr/src/.npm/
RUN npm install -g @vue/cli
ENV NODE_ENV=dev
RUN npm run build
 
FROM nginx:1.25.1
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY --from=builder /usr/src/app/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
ENTRYPOINT ["nginx", "-g", "daemon off;"]
